services:
  mysql:
    image: mysql:8.0
    container_name: rootmatching-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dgu_backend
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake